### ISSUE TITLE
Calculate cyclic complexity for function #2: NetData.NetMessage.Builder.clear()

### ISSUE THREAD

**Issue by EdvinArdo** [DD2480-Group17/assignment3#8]
Cxty = pi - s + 2 = 1*21 - 1 + 2 = 22

**Comment by johannaii** [comment]
Is the function just complex, or also long?
What is the purpose of the function?

**Comment by georgewbar** [comment]
1. What are your results? Did everyone get the same result? Is there something that is unclear? If you have a tool, is its result the same as yours?
Cxty = pi - s + 2 = 1*21 - 1 + 2 = 22.
Yes. Everyone got the same results.
No. There is nothing unclear.
We used Jacoco, and the result was the same.

2. Are the functions/methods with high CC also very long in terms of LOC?
Yes. The number of lines is about 129 lines.

3. What is the purpose of these functions? Is it related to the high CC?
This function is related to `called by the initialization and clear code paths to allow subclasses to reset any of their builtin fields back to the initial values.` The reason for such high CC is that there are a lot of if-statements to check if the fields are not null. If they are null, they are initialized. Otherwise, clear method is called on a field if it is not null. However, there is a lot of code duplication. And, the problem should not have high essential complexity after refactoring. 

4. If your programming language uses exceptions: Are they taken into account by the tool? If you think of an exception as another possible branch (to the catch block or the end of the function), how is the CC affected?
As per Jacoco's documentation, "Note that as JaCoCo does not consider exception handling as branches try/catch blocks will also not increase complexity" is said under cyclomatic complexity. If exceptions are considered as branches, the cyclomatic complexity calculated will increase in general. However, in the NetData.NetMessage.Builder.clear(), there are no exceptions thrown. Therefore, the cyclomatic complexity will be the same regardless of whether exceptions are considered as branches or not.

5. Is the documentation of the function clear about the different possible outcomes induced by different branches taken?
It is relatively clear. However, i had to read through the code a bit to get an idea about the how the documentation maps to the code.
